name: Supabase Keep Alive

on:
  schedule:
    # S'exécute tous les lundis et jeudis à 8h00 UTC
    - cron: '0 8 * * 1,4'
  workflow_dispatch: # Permet de le lancer manuellement si besoin

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          pip install supabase
          
      - name: Run maintenance script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          # On garde l'ancienne au cas où, mais on ajoute la nouvelle
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }} 
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        run: python utils/maintenance.py
